### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by gkaf89** [georgios-stats/UTOPIAE-Bayes#1]
I suspect there is a typo in file [`chapter_content_free.pdf`](https://github.com/georgios-stats/UTOPIAE-Bayes/blob/master/chapter_content_free.pdf) in equation (1.2):
```
\pi ( d \theta \| ... ) -> d \pi ( \theta \| ... )
```

**Comment by georgios-stats** [comment]
This notation is used as well. Thanks

**Comment by gkaf89** [comment]
Thanks! I am closing the issue.
